"""add phase 3 multi-tenant franchisors and user roles

Revision ID: 202281ad12d6
Revises: 393c656a3b98
Create Date: 2026-09-04 12:55:58.381164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202281ad12d6'
down_revision: Union[str, Sequence[str], None] = '393c656a3b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('tax_office', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franchisors_id'), 'franchisors', ['id'], unique=False)
    op.add_column('branches', sa.Column('franchisor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_branches_franchisor_id'), 'branches', ['franchisor_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'franchisors', ['franchisor_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='FRANCHISOR_ADMIN'))
    op.add_column('users', sa.Column('franchisor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_franchisor_id'), 'users', ['franchisor_id'], unique=False)
    op.create_foreign_key(None, 'users', 'franchisors', ['franchisor_id'], ['id'])
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_franchisor_id'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'branch_id')
    op.drop_column('users', 'franchisor_id')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_franchisor_id'), table_name='branches')
    op.drop_column('branches', 'franchisor_id')
    op.drop_index(op.f('ix_franchisors_id'), table_name='franchisors')
    op.drop_table('franchisors')
    # ### end Alembic commands ###
