"""Add period_settings table

Revision ID: 8b49b8c9bd9f
Revises: f1768cd1f448
Create Date: 2026-09-04 10:42:44.111136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b49b8c9bd9f'
down_revision: Union[str, Sequence[str], None] = 'f1768cd1f448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('collector_party', sa.String(length=50), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'year', 'month', name='uq_branch_period')
    )
    op.create_index(op.f('ix_period_settings_branch_id'), 'period_settings', ['branch_id'], unique=False)
    op.create_index(op.f('ix_period_settings_id'), 'period_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_settings_id'), table_name='period_settings')
    op.drop_index(op.f('ix_period_settings_branch_id'), table_name='period_settings')
    op.drop_table('period_settings')
    # ### end Alembic commands ###
